import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./context/providers";
import SessionProvider from "./context/sessionProvider";
import { getServerSession } from "next-auth";
import { authConfig } from "@/auth.config";
import { NextUIProviderClient } from "./context/nextUiProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authConfig);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#EF5350" />
        <SessionProvider session={session}>
          <Providers>
            <NextUIProviderClient>{children}</NextUIProviderClient>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
